##################################################################################################
# To run this script
# cd ~/git/BS_MicrobiomeAnalysis_2022/analysis/BLJ_config_files
# biolockj -d microbiome_sex_analysis.properties
# biolockj -d -c microbiome_sex_analysis.properties -r ${BLJ_PROJ}/microbiome_sex_analysis_*
##################################################################################################

# make sure memory is set to 16GB
# Docker > Preferences > Resources

genMod.launcher=Rscript
pipeline.inputTypes=other
pipeline.copyInput=Y

input.dirPaths=../input/
input.allowDuplicateNames=Y
Rfunc=../RScripts/functions.R

#BioModule biolockj.module.diy.GenMod AS PatientCharacteristics
PatientCharacteristics.scriptPath = ../RScripts/PatientCharacteristics.R
# PatientCharacteristics.param=weight_update.txt
PatientCharacteristics.param=BLJ weight_update_BLonly_excluded.txt
PatientCharacteristics.resources=${Rfunc}
PatientCharacteristics.imageOwner=asorgen
PatientCharacteristics.imageTag=v5
PatientCharacteristics.imageName=gg-tidyr

#BioModule biolockj.module.diy.GenMod AS BMI_Results
BMI_Results.scriptPath = ../RScripts/BMI_Results.R
BMI_Results.param=BLJ weight_update_BLonly_excluded.txt
BMI_Results.resources=${Rfunc}
BMI_Results.imageOwner=asorgen
BMI_Results.imageTag=v5
BMI_Results.imageName=gg-tidyr

#BioModule biolockj.module.diy.GenMod AS ExcessWeightLoss
ExcessWeightLoss.scriptPath = ../RScripts/ExcessWeightLoss.R
ExcessWeightLoss.param=BLJ
ExcessWeightLoss.resources=${Rfunc}
ExcessWeightLoss.imageOwner=asorgen
ExcessWeightLoss.imageTag=v5
ExcessWeightLoss.imageName=gg-tidyr

#BioModule biolockj.module.diy.GenMod AS WeightMetaMerge
WeightMetaMerge.scriptPath=../RScripts/WeightMetaMerge.R
WeightMetaMerge.imageOwner=asorgen
WeightMetaMerge.imageTag=v4
WeightMetaMerge.imageName=gg-tidyr
WeightMetaMerge.param=BLJ
WeightMetaMerge.resources=${Rfunc}

#BioModule biolockj.module.diy.GenMod AS Barplot_WLgroups
Barplot_WLgroups.scriptPath=../RScripts/Barplot_WLgroups.R
Barplot_WLgroups.param=BLJ
Barplot_WLgroups.resources=${Rfunc}
Barplot_WLgroups.imageOwner=asorgen
Barplot_WLgroups.imageTag=v5
Barplot_WLgroups.imageName=gg-tidyr

#BioModule biolockj.module.diy.GenMod AS Tertile_Ranks
Tertile_Ranks.scriptPath = ../RScripts/Tertile_Ranks.R
Tertile_Ranks.param=BLJ
Tertile_Ranks.resources=${Rfunc}
Tertile_Ranks.imageOwner=asorgen
Tertile_Ranks.imageTag=v5
Tertile_Ranks.imageName=gg-tidyr

#BioModule biolockj.module.diy.GenMod AS General_Weight_Stats
General_Weight_Stats.scriptPath = ../RScripts/General_Weight_Stats.R
General_Weight_Stats.param=BLJ 0 1 6 12 18 24
General_Weight_Stats.resources=${Rfunc}
General_Weight_Stats.imageOwner=asorgen
General_Weight_Stats.imageTag=v5
General_Weight_Stats.imageName=gg-tidyr





#BioModule biolockj.module.diy.GenMod AS MetaPhlAn2_TaxaMetaMerge
MetaPhlAn2_TaxaMetaMerge.scriptPath=../RScripts/TaxaMetaMerge.R
MetaPhlAn2_TaxaMetaMerge.imageOwner=asorgen
MetaPhlAn2_TaxaMetaMerge.imageTag=v4
MetaPhlAn2_TaxaMetaMerge.imageName=gg-tidyr
MetaPhlAn2_TaxaMetaMerge.param=BLJ MetaPhlAn2
MetaPhlAn2_TaxaMetaMerge.resources=${Rfunc}





#BioModule biolockj.module.diy.GenMod AS MetaPhlAn2_Diversity_Metrics
MetaPhlAn2_Diversity_Metrics.scriptPath = ../RScripts/Diversity_Metrics.R
MetaPhlAn2_Diversity_Metrics.param=BLJ MetaPhlAn2
MetaPhlAn2_Diversity_Metrics.resources=${Rfunc}
MetaPhlAn2_Diversity_Metrics.imageOwner=asorgen
MetaPhlAn2_Diversity_Metrics.imageTag=v5
MetaPhlAn2_Diversity_Metrics.imageName=gg-tidyr





#BioModule biolockj.module.diy.GenMod AS MetaPhlAn2_Taxa_by_Sex
MetaPhlAn2_Taxa_by_Sex.scriptPath = ../RScripts/Taxa_by_Sex.R
MetaPhlAn2_Taxa_by_Sex.param=BLJ MetaPhlAn2 0 1 6 12 18 24
MetaPhlAn2_Taxa_by_Sex.resources=${Rfunc}
MetaPhlAn2_Taxa_by_Sex.imageOwner=asorgen
MetaPhlAn2_Taxa_by_Sex.imageTag=v5
MetaPhlAn2_Taxa_by_Sex.imageName=gg-tidyr

