##################################################################################################
# To run this script
# cd ~/git/BS_Microbiome_Analysis/analysis/BLJ_config_files
# biolockj --blj -d quintile_analysis.properties
# biolockj --blj -d -c quintile_analysis.properties -r ${BLJ_PROJ}/quintile_analysis_*
##################################################################################################

# make sure memory is set to 16GB
# Docker > Preferences > Resources

genMod.launcher=Rscript
pipeline.inputTypes=other
pipeline.copyInput=Y

input.dirPaths=../input/
input.allowDuplicateNames=Y
Rfunc=../RScripts/functions.R
# metaVariables=AverageDailyMVPAUnbouted AverageDailyMVPABoutTroiano AverageDailyLight AverageDailySedentaryUnbouted AverageDailySedentary30min AverageDailySteps

#BioModule biolockj.module.diy.GenMod AS PatientCharacteristics
PatientCharacteristics.scriptPath = ../RScripts/PatientCharacteristics.R
# PatientCharacteristics.param=weight_update.txt
PatientCharacteristics.param=BLJ weight_update_BLonly_excluded.txt
PatientCharacteristics.resources=${Rfunc}
PatientCharacteristics.imageOwner=asorgen
PatientCharacteristics.imageTag=v5
PatientCharacteristics.imageName=gg-tidyr

#BioModule biolockj.module.diy.GenMod AS BMI_Results
BMI_Results.scriptPath = ../RScripts/BMI_Results.R
BMI_Results.param=BLJ weight_update_BLonly_excluded.txt
BMI_Results.resources=${Rfunc}
BMI_Results.imageOwner=asorgen
BMI_Results.imageTag=v5
BMI_Results.imageName=gg-tidyr

#BioModule biolockj.module.diy.GenMod AS ExcessWeightLoss
ExcessWeightLoss.scriptPath = ../RScripts/ExcessWeightLoss.R
ExcessWeightLoss.param=BLJ
ExcessWeightLoss.resources=${Rfunc}
ExcessWeightLoss.imageOwner=asorgen
ExcessWeightLoss.imageTag=v5
ExcessWeightLoss.imageName=gg-tidyr

#BioModule biolockj.module.diy.GenMod AS WeightMetaMerge
WeightMetaMerge.scriptPath=../RScripts/WeightMetaMerge.R
WeightMetaMerge.imageOwner=asorgen
WeightMetaMerge.imageTag=v4
WeightMetaMerge.imageName=gg-tidyr
WeightMetaMerge.param=BLJ
WeightMetaMerge.resources=${Rfunc}

#BioModule biolockj.module.diy.GenMod AS Barplot_WLgroups
Barplot_WLgroups.scriptPath=../RScripts/Barplot_WLgroups.R
Barplot_WLgroups.param=BLJ
Barplot_WLgroups.resources=${Rfunc}
Barplot_WLgroups.imageOwner=asorgen
Barplot_WLgroups.imageTag=v5
Barplot_WLgroups.imageName=gg-tidyr

#BioModule biolockj.module.diy.GenMod AS Quintile_Ranks
Quintile_Ranks.scriptPath = ../RScripts/Quintile_Ranks.R
Quintile_Ranks.param=BLJ
Quintile_Ranks.resources=${Rfunc}
Quintile_Ranks.imageOwner=asorgen
Quintile_Ranks.imageTag=v5
Quintile_Ranks.imageName=gg-tidyr

# # BioModule biolockj.module.diy.GenMod AS Quartile_Ranks
# Quartile_Ranks.scriptPath = ../RScripts/Quartile_Ranks.R
# # Quartile_Ranks.param=MetaPhlAn2
# Quartile_Ranks.resources=${Rfunc}
# Quartile_Ranks.imageOwner=asorgen
# Quartile_Ranks.imageTag=v5
# Quartile_Ranks.imageName=gg-tidyr

# #BioModule biolockj.module.diy.GenMod AS Third_Ranks
# Third_Ranks.scriptPath = ../RScripts/Third_Ranks.R
# # Third_Ranks.param=MetaPhlAn2
# Third_Ranks.resources=${Rfunc}
# Third_Ranks.imageOwner=asorgen
# Third_Ranks.imageTag=v5
# Third_Ranks.imageName=gg-tidyr

# #BioModule biolockj.module.diy.GenMod AS Half_Ranks
# Half_Ranks.scriptPath = ../RScripts/Half_Ranks.R
# # Half_Ranks.param=MetaPhlAn2
# Half_Ranks.resources=${Rfunc}
# Half_Ranks.imageOwner=asorgen
# Half_Ranks.imageTag=v5
# Half_Ranks.imageName=gg-tidyr

#BioModule biolockj.module.diy.GenMod AS MetaPhlAn2_TaxaMetaMerge
MetaPhlAn2_TaxaMetaMerge.scriptPath=../RScripts/TaxaMetaMerge.R
MetaPhlAn2_TaxaMetaMerge.imageOwner=asorgen
MetaPhlAn2_TaxaMetaMerge.imageTag=v4
MetaPhlAn2_TaxaMetaMerge.imageName=gg-tidyr
MetaPhlAn2_TaxaMetaMerge.param=BLJ MetaPhlAn2
MetaPhlAn2_TaxaMetaMerge.resources=${Rfunc}

#BioModule biolockj.module.diy.GenMod AS MetaPhlAn2_Taxa_over_time_BLto24
MetaPhlAn2_Taxa_over_time_BLto24.scriptPath = ../RScripts/Taxa_over_time.R
MetaPhlAn2_Taxa_over_time_BLto24.param=BLJ MetaPhlAn2 0 1 6 12 18 24
MetaPhlAn2_Taxa_over_time_BLto24.resources=${Rfunc}
MetaPhlAn2_Taxa_over_time_BLto24.imageOwner=asorgen
MetaPhlAn2_Taxa_over_time_BLto24.imageTag=v5
MetaPhlAn2_Taxa_over_time_BLto24.imageName=gg-tidyr

#BioModule biolockj.module.diy.GenMod AS MetaPhlAn2_Taxa_over_time_BLto12
MetaPhlAn2_Taxa_over_time_BLto12.scriptPath = ../RScripts/Taxa_over_time.R
MetaPhlAn2_Taxa_over_time_BLto12.param=BLJ MetaPhlAn2 0 1 6 12
MetaPhlAn2_Taxa_over_time_BLto12.resources=${Rfunc}
MetaPhlAn2_Taxa_over_time_BLto12.imageOwner=asorgen
MetaPhlAn2_Taxa_over_time_BLto12.imageTag=v5
MetaPhlAn2_Taxa_over_time_BLto12.imageName=gg-tidyr

# #BioModule biolockj.module.diy.GenMod AS MetaPhlAn2_BL_Taxa_Predictions
# MetaPhlAn2_BL_Taxa_Predictions.scriptPath = ../RScripts/BL_Taxa_Predictions.R
# MetaPhlAn2_BL_Taxa_Predictions.param=MetaPhlAn2 0 1 6 12 18 24
# MetaPhlAn2_BL_Taxa_Predictions.resources=${Rfunc}
# MetaPhlAn2_BL_Taxa_Predictions.imageOwner=asorgen
# MetaPhlAn2_BL_Taxa_Predictions.imageTag=v5
# MetaPhlAn2_BL_Taxa_Predictions.imageName=gg-tidyr

# #BioModule biolockj.module.diy.GenMod AS MetaPhlAn2_Taxa_Changes_1M
# MetaPhlAn2_Taxa_Changes_1M.scriptPath = ../RScripts/Taxa_Changes_1M.R
# MetaPhlAn2_Taxa_Changes_1M.param=MetaPhlAn2
# MetaPhlAn2_Taxa_Changes_1M.resources=${Rfunc}
# MetaPhlAn2_Taxa_Changes_1M.imageOwner=asorgen
# MetaPhlAn2_Taxa_Changes_1M.imageTag=v5
# MetaPhlAn2_Taxa_Changes_1M.imageName=gg-tidyr


# #BioModule biolockj.module.diy.GenMod AS MetaPhlAn2_Microbiome_WeightLoss_Associations_uLM
# MetaPhlAn2_Microbiome_WeightLoss_Associations_uLM.scriptPath = ../RScripts/Microbiome_WeightLoss_Associations_uLM.R
# MetaPhlAn2_Microbiome_WeightLoss_Associations_uLM.param=MetaPhlAn2 0 1 6 12 18 24
# MetaPhlAn2_Microbiome_WeightLoss_Associations_uLM.resources=${Rfunc}
# MetaPhlAn2_Microbiome_WeightLoss_Associations_uLM.imageOwner=asorgen
# MetaPhlAn2_Microbiome_WeightLoss_Associations_uLM.imageTag=v5
# MetaPhlAn2_Microbiome_WeightLoss_Associations_uLM.imageName=gg-tidyr


# #BioModule biolockj.module.diy.GenMod AS MetaPhlAn2_Microbiome_WeightLoss_Associations_kendall
# MetaPhlAn2_Microbiome_WeightLoss_Associations_kendall.scriptPath = ../RScripts/Microbiome_WeightLoss_Associations_kendall.R
# MetaPhlAn2_Microbiome_WeightLoss_Associations_kendall.param=MetaPhlAn2 0 1 6 12 18 24
# MetaPhlAn2_Microbiome_WeightLoss_Associations_kendall.resources=${Rfunc}
# MetaPhlAn2_Microbiome_WeightLoss_Associations_kendall.imageOwner=asorgen
# MetaPhlAn2_Microbiome_WeightLoss_Associations_kendall.imageTag=v5
# MetaPhlAn2_Microbiome_WeightLoss_Associations_kendall.imageName=gg-tidyr


#BioModule biolockj.module.diy.GenMod AS Kraken2_TaxaMetaMerge
Kraken2_TaxaMetaMerge.scriptPath=../RScripts/TaxaMetaMerge.R
Kraken2_TaxaMetaMerge.imageOwner=asorgen
Kraken2_TaxaMetaMerge.imageTag=v4
Kraken2_TaxaMetaMerge.imageName=gg-tidyr
Kraken2_TaxaMetaMerge.param=BLJ Kraken2
Kraken2_TaxaMetaMerge.resources=${Rfunc}

#BioModule biolockj.module.diy.GenMod AS Kraken2_Taxa_over_time_BLto24
Kraken2_Taxa_over_time_BLto24.scriptPath = ../RScripts/Taxa_over_time.R
Kraken2_Taxa_over_time_BLto24.param=BLJ Kraken2 0 1 6 12 18 24
Kraken2_Taxa_over_time_BLto24.resources=${Rfunc}
Kraken2_Taxa_over_time_BLto24.imageOwner=asorgen
Kraken2_Taxa_over_time_BLto24.imageTag=v5
Kraken2_Taxa_over_time_BLto24.imageName=gg-tidyr

#BioModule biolockj.module.diy.GenMod AS Kraken2_Taxa_over_time_BLto12
Kraken2_Taxa_over_time_BLto12.scriptPath = ../RScripts/Taxa_over_time.R
Kraken2_Taxa_over_time_BLto12.param=BLJ Kraken2 0 1 6 12
Kraken2_Taxa_over_time_BLto12.resources=${Rfunc}
Kraken2_Taxa_over_time_BLto12.imageOwner=asorgen
Kraken2_Taxa_over_time_BLto12.imageTag=v5
Kraken2_Taxa_over_time_BLto12.imageName=gg-tidyr